### ISSUE TITLE
App Crashes on Lib 2.8.2 - Android 8.1.0 - RN 0.59.10

### ISSUE THREAD

**Issue by blacksheep--** [webyonet/react-native-android-location-services-dialog-box#79]
The app crashes on a Blackberry with:
- `Android 8.1.0`
- `RN 0.59.10`
- `Lib Version 2.8.2`

It fails with the following Exception and trace:

    FATAL EXCEPTION: mqt_native_modules
    Process: com.app, PID: 13970
    com.facebook.react.bridge.NoSuchKeyException: message
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:137)
        at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:141)
        at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:192)
        at com.showlocationservicesdialogbox.LocationServicesDialogBoxModule.displayPromptForEnablingGPS(LocationServicesDialogBoxModule.java:106)
        at com.showlocationservicesdialogbox.LocationServicesDialogBoxModule.checkLocationService(LocationServicesDialogBoxModule.java:84)
        at com.showlocationservicesdialogbox.LocationServicesDialogBoxModule.checkLocationServicesIsEnabled(LocationServicesDialogBoxModule.java:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)

**Comment by webyonet** [comment]
message,ok and cancel fields is required.
you should not leave these values ​​empty
